/*
 * Copyright (C) 2007 National Association of REALTORS(R)
 *
 * All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, and/or sell copies of the
 * Software, and to permit persons to whom the Software is furnished
 * to do so, provided that the above copyright notice(s) and this
 * permission notice appear in all copies of the Software and that
 * both the above copyright notice(s) and this permission notice
 * appear in supporting documentation.
 */

// This file was generated by the gettypename_gen.rb script in the
// tools directory of the ezRETS source.

#include "utils.h"
#include <boost/lexical_cast.hpp>

using std::string;

string getTypeName(SQLSMALLINT type)
{
    string result;
    switch (type)
    {
<%- for define in defines -%>
        case <%= define %>:
            result = "<%= define %>";
            break;
<%- end -%>
        default:
            result = boost::lexical_cast<std::string>(type);
            break;
    };

    return result;
}
